"""
Stage 3: the actual AlphaZero-style closed loop, tying stages 1 and 2
together - self-play games generated by the network-guided MCTS, whose own
search outputs (visit-count distribution, final game result) become the
network's next training targets. This is the one piece our project never
had before: the network and the search continuously improving each other,
rather than separately-tested, hand-glued components.

One self-play game:
  - At each move, run neural_mcts_search from the current position.
  - Record (encoded input, visit-count policy distribution) for that position.
  - Play the chosen move (sampled from the visit distribution early in the
    game for exploration diversity, greedy/most-visited later - the same
    temperature idea AlphaZero uses).
  - Once the game ends, back-fill every recorded position with the REAL
    final outcome (from that position's own mover's perspective) as its
    value training target - a Monte Carlo-style target, matching what
    AlphaZero's own value network actually uses (see the "one interesting
    similarity" note from the research conversation).
"""

import random

import numpy as np

from game_engine import SlidingTicTacToe, X, O
from neural_net import TicTacToeNet, encode_state, encode_action, POLICY_SIZE
from neural_mcts import neural_mcts_search, visit_count_policy
from perfect_solver import negamax_value, best_move as perfect_solver_move


def play_one_selfplay_game(net, iterations=100, temperature_moves=6, teacher_side=None, noise_frac=0.25,
                            extra_iterations_side=None, extra_iterations_multiplier=2.0,
                            imitate_teacher_policy=False):
    """Returns a list of (input_vector, policy_target, mover) for every
    position visited, plus the game's winner (mover identity or -1 for draw) -
    the value target is filled in by the caller once the winner is known,
    since it depends on each position's own mover.

    teacher_side: if set to X or O, that side's ACTUAL move (not its policy
    target) is supplied by the perfect solver instead of sampled from the
    network's own search. This targets the diagnosed root cause of the X/O
    imbalance directly (see research/alphazero_deep_dive/04) - rebalancing
    training data can't manufacture examples of strong play that were never
    generated; this makes sure strong play for the weaker side actually
    happens during generation, so the resulting positions and outcomes
    reflect genuine correct defense instead of the network's own current
    (weak) choices. The network's own policy/value targets are still
    recorded normally at every position, including the teacher-played side's
    - only the move actually taken is overridden.

    imitate_teacher_policy: if True (only meaningful together with
    teacher_side), the recorded POLICY target at the teacher-controlled
    side's positions is also overridden - a one-hot distribution on the
    solver's actual chosen move, instead of the network's own (potentially
    still weak) MCTS visit distribution. This is the direct fix for the
    "policy imitation, not just value calibration" gap found in the plain
    teacher run (research/alphazero_deep_dive/05_results_summary.md, Stage
    3): teacher_side alone only ever corrects the game's *continuation* (so
    the value head learns from genuinely strong play), but never tells the
    policy head "this exact move was correct here" - so the policy head
    never learns to reproduce the solver's choice. This flag closes that gap
    at its source.

    extra_iterations_side: if set to X or O, that side gets
    extra_iterations_multiplier times the normal MCTS iteration budget on its
    own turns - a cheap way to partially compensate weaker knowledge with
    more search "thinking," producing better games for that side to learn
    from without touching the training/rebalancing machinery at all."""
    game = SlidingTicTacToe()
    examples = []  # (input_vector, policy_target, mover)
    move_number = 0

    while not game.game_over:
        this_move_iterations = iterations
        if extra_iterations_side is not None and game.current_player == extra_iterations_side:
            this_move_iterations = int(iterations * extra_iterations_multiplier)
        move, root = neural_mcts_search(game, net, iterations=this_move_iterations, add_noise=True, noise_frac=noise_frac)

        temperature = 1.0 if move_number < temperature_moves else 0.1
        policy_target = visit_count_policy(root, temperature=temperature)

        is_teacher_move = teacher_side is not None and game.current_player == teacher_side
        if is_teacher_move:
            move = perfect_solver_move(game)  # override: play the objectively correct move
            if imitate_teacher_policy:
                # One-hot the policy target on the solver's actual choice, so the
                # policy head is directly trained to reproduce this move here -
                # not just left to infer it indirectly via the value head.
                policy_target = np.zeros(POLICY_SIZE)
                policy_target[encode_action(move)] = 1.0

        x = encode_state(game.board, game.phase, game.current_player)
        examples.append((x, policy_target, game.current_player))

        if is_teacher_move:
            pass  # move already set above
        elif temperature > 0.5:
            # Sample proportional to the (temperature-adjusted) visit distribution -
            # exploration diversity early in the game, same idea as AlphaZero.
            legal_moves = list(root.children.keys())
            legal_indices = [encode_action(m) for m in legal_moves]
            probs = np.array([policy_target[i] for i in legal_indices])
            probs = probs / probs.sum()
            move = legal_moves[np.random.choice(len(legal_moves), p=probs)]

        game.make_move(move)
        move_number += 1

    winner = game.winner
    training_examples = []
    for x, policy_target, mover in examples:
        if winner == -1:
            value_target = 0.0
        else:
            value_target = 1.0 if winner == mover else -1.0
        training_examples.append((x, policy_target, value_target, mover))  # mover kept for X/O rebalancing

    return training_examples, winner


def value_error_vs_solver(net, sample_states, sample_size=300):
    """Same idea as the dashboard's compute_value_error, but for the
    network: mean |net's value - solver's exact value| over a random sample
    of real states - the network's own version of the project's core
    'training loss' metric."""
    keys = random.sample(list(sample_states.keys()), min(sample_size, len(sample_states)))
    total_error = 0.0
    for board, phase, player in keys:
        game = SlidingTicTacToe()
        game.board = list(board)
        game.phase = phase
        game.current_player = player
        true_value = negamax_value(game)
        pred_value, _ = net.predict(board, phase, player)
        total_error += abs(pred_value - true_value)
    return total_error / len(keys)


def value_error_vs_solver_by_mover(net, sample_states, sample_size=300):
    """Same as value_error_vs_solver, but split by whose turn it is at each
    sampled state - the direct diagnostic for whether a fix is actually
    closing the X/O gap, rather than just moving an aggregate number that
    could mask a persistent asymmetry (this was flagged as an open question
    in research/alphazero_deep_dive/05_results_summary.md)."""
    keys = random.sample(list(sample_states.keys()), min(sample_size, len(sample_states)))
    errors = {X: [], O: []}
    for board, phase, player in keys:
        game = SlidingTicTacToe()
        game.board = list(board)
        game.phase = phase
        game.current_player = player
        true_value = negamax_value(game)
        pred_value, _ = net.predict(board, phase, player)
        errors[player].append(abs(pred_value - true_value))
    err_x = sum(errors[X]) / len(errors[X]) if errors[X] else None
    err_o = sum(errors[O]) / len(errors[O]) if errors[O] else None
    return err_x, err_o


def win_rate_freeze_decision(o_win_rate_history, freeze_threshold=0.15, unfreeze_threshold=0.30,
                              window=10, currently_frozen=False):
    """Hysteresis-gated freeze decision based on O's own ROLLING WIN RATE (not value
    calibration - see the 'catchup' run in research/alphazero_deep_dive/05_results_summary.md,
    where gating on value_error_vs_solver_by_mover almost never triggered because
    calibration and win rate are decoupled in this build). Freezes X's training whenever
    O has been losing badly over a recent window of iterations, unfreezes once O has
    genuinely recovered - using two different thresholds (not one) specifically to avoid
    rapid flapping if the win rate hovers in between: once frozen, it takes a clearly
    better win rate (unfreeze_threshold), not just a marginally better one, to unfreeze.

    o_win_rate_history: a sequence of per-iteration O win rates (wins_O / games_played),
    oldest first. Only the most recent `window` entries are used.

    Returns True (should be frozen this iteration) or False."""
    if len(o_win_rate_history) < window:
        return False  # not enough data yet to judge a trend - never freeze prematurely
    recent = list(o_win_rate_history)[-window:]
    rolling_win_rate = sum(recent) / len(recent)
    if currently_frozen:
        return rolling_win_rate < unfreeze_threshold  # stay frozen until O clearly recovers
    return rolling_win_rate < freeze_threshold  # only freeze once O is clearly struggling


def balance_by_mover(examples):
    """Fix for the X/O skill asymmetry (research/10_alphazero_style_implementation.md):
    self-play naturally produces more decisive X-to-move examples than O-to-move
    ones, since X has a real, provable first-move advantage - left alone, the
    shared network gets disproportionately more 'how to attack as X' signal
    than 'how to defend as O' signal, and that imbalance compounds over time.
    Oversample (with replacement) whichever side is under-represented so every
    training batch sees a roughly equal split of both roles."""
    by_mover = {X: [], O: []}
    for example in examples:
        by_mover[example[3]].append(example)

    if not by_mover[X] or not by_mover[O]:
        return examples  # nothing to balance yet (e.g. very first iteration)

    majority_side = X if len(by_mover[X]) >= len(by_mover[O]) else O
    minority_side = O if majority_side == X else X
    target_count = len(by_mover[majority_side])

    oversampled_minority = random.choices(by_mover[minority_side], k=target_count)
    return by_mover[majority_side] + oversampled_minority


def train_on_examples(net, examples, batch_size=64, learning_rate=0.001):
    examples = balance_by_mover(examples)
    random.shuffle(examples)
    total_value_loss = 0.0
    total_policy_loss = 0.0
    n_batches = 0

    for i in range(0, len(examples), batch_size):
        batch = examples[i:i + batch_size]
        x_batch = np.array([e[0] for e in batch])
        policy_batch = np.array([e[1] for e in batch])
        value_batch = np.array([[e[2]] for e in batch])
        legal_mask = (policy_batch > 0).astype(float)
        # Policy targets can have exact zeros for moves that were never
        # visited even though legal - only mask out truly illegal actions,
        # so recompute the mask from which entries could possibly be legal:
        # simplest robust approach here is to treat any position with a
        # nonzero target OR that appears in the recorded distribution as
        # legal; since visit_count_policy already zeroes illegal actions,
        # using (policy_batch > 0) undercounts legal-but-unvisited moves.
        # We accept this approximation for now - see research notes.
        value_loss, policy_loss = net.train_step(x_batch, value_batch, policy_batch, legal_mask, learning_rate)
        total_value_loss += value_loss
        total_policy_loss += policy_loss
        n_batches += 1

    return total_value_loss / n_batches, total_policy_loss / n_batches


if __name__ == "__main__":
    import csv
    import os
    import sys
    import time
    from collections import deque

    from perfect_solver import _enumerate_states, _value_iteration

    print("Loading solver states for value-error benchmarking...", flush=True)
    states, transitions = _enumerate_states()
    values, _ = _value_iteration(states, transitions)

    NUM_ITERATIONS = int(sys.argv[1]) if len(sys.argv) > 1 else 300
    RUN_NAME = sys.argv[2] if len(sys.argv) > 2 else 'teacher'
    TEMPERATURE_MOVES = int(sys.argv[3]) if len(sys.argv) > 3 else 6
    NOISE_FRAC = float(sys.argv[4]) if len(sys.argv) > 4 else 0.25
    GAMES_PER_ITERATION = 20
    MCTS_ITERS = 100
    CHECKPOINT_EVERY = 5
    REPLAY_BUFFER_SIZE = 8000  # keep several iterations' worth of examples, not just the latest
    TEACHER_SIDE = O if RUN_NAME in ('teacher', 'imitate') else None  # teacher + imitate both use O as the teacher-played side
    EXTRA_ITERATIONS_SIDE = O if RUN_NAME == 'o_compute' else None  # double MCTS budget for O's own turns
    IMITATE_TEACHER_POLICY = RUN_NAME == 'imitate'  # also one-hot the policy target on the teacher's move

    log_path = f'selfplay_training_log_{RUN_NAME}.csv'

    print(f"Run '{RUN_NAME}': iterations={NUM_ITERATIONS}, temperature_moves={TEMPERATURE_MOVES}, "
          f"noise_frac={NOISE_FRAC}, teacher_side={TEACHER_SIDE}, extra_iterations_side={EXTRA_ITERATIONS_SIDE}, "
          f"imitate_teacher_policy={IMITATE_TEACHER_POLICY}",
          flush=True)

    log_is_new = not os.path.exists(log_path)
    log_file = open(log_path, 'a', newline='')
    log_writer = csv.writer(log_file)
    if log_is_new:
        header = ['iteration', 'wins_X', 'wins_O', 'draws',
                   'buffer_size', 'value_loss', 'policy_loss',
                   'value_error_vs_solver', 'value_error_X', 'value_error_O',
                   'elapsed_sec']
        if RUN_NAME == 'catchup_wr':
            header += ['x_frozen', 'o_win_rate_rolling']
        log_writer.writerow(header)

    start_time = time.time()

    if RUN_NAME == 'twonet':
        # Two completely separate networks, one per role - removes the "shared
        # weights get dominated by whichever side is winning more" mechanism
        # entirely, at the cost of the canonicalization trick's cross-role
        # transfer (X's learned patterns no longer help O at all, or vice versa).
        net_x = TicTacToeNet(hidden_size=64, seed=42)
        net_o = TicTacToeNet(hidden_size=64, seed=43)
        nets = {X: net_x, O: net_o}
        buffer_x = deque(maxlen=REPLAY_BUFFER_SIZE)
        buffer_o = deque(maxlen=REPLAY_BUFFER_SIZE)

        for iteration in range(NUM_ITERATIONS):
            iter_start = time.time()
            results = {'X': 0, 'O': 0, 'draw': 0}

            for _ in range(GAMES_PER_ITERATION):
                examples, winner = play_one_selfplay_game(nets, iterations=MCTS_ITERS,
                                                           temperature_moves=TEMPERATURE_MOVES, noise_frac=NOISE_FRAC)
                for ex in examples:
                    (buffer_x if ex[3] == X else buffer_o).append(ex)
                if winner == -1:
                    results['draw'] += 1
                elif winner == X:
                    results['X'] += 1
                else:
                    results['O'] += 1

            # No rebalancing needed or possible here - each buffer only ever
            # contains its own role's examples; balance_by_mover (inside
            # train_on_examples) safely no-ops when one side is empty.
            value_loss_x, policy_loss_x = train_on_examples(net_x, list(buffer_x))
            value_loss_o, policy_loss_o = train_on_examples(net_o, list(buffer_o))
            err_x, _ = value_error_vs_solver_by_mover(net_x, values)  # net_x's opinion of O-states is meaningless - discard
            _, err_o = value_error_vs_solver_by_mover(net_o, values)  # net_o's opinion of X-states is meaningless - discard
            err = (err_x + err_o) / 2
            value_loss = (value_loss_x + value_loss_o) / 2
            policy_loss = (policy_loss_x + policy_loss_o) / 2
            elapsed = time.time() - iter_start

            print(f"iter {iteration + 1:>4}/{NUM_ITERATIONS}: games={results}, "
                  f"buffer_x={len(buffer_x)}, buffer_o={len(buffer_o)}, "
                  f"value_loss={value_loss:.4f}, policy_loss={policy_loss:.4f}, "
                  f"value_error_vs_solver={err:.4f} (X={err_x:.4f}, O={err_o:.4f}), elapsed={elapsed:.1f}s", flush=True)

            log_writer.writerow([iteration + 1, results['X'], results['O'], results['draw'],
                                  len(buffer_x) + len(buffer_o), value_loss, policy_loss, err, err_x, err_o, elapsed])
            log_file.flush()

            if (iteration + 1) % CHECKPOINT_EVERY == 0:
                net_x.save(f'selfplay_trained_net_{RUN_NAME}_X.pkl')
                net_o.save(f'selfplay_trained_net_{RUN_NAME}_O.pkl')

        net_x.save(f'selfplay_trained_net_{RUN_NAME}_X.pkl')
        net_o.save(f'selfplay_trained_net_{RUN_NAME}_O.pkl')
        log_file.close()
        print(f"Done. Total time: {time.time() - start_time:.1f}s. "
              f"Saved to selfplay_trained_net_{RUN_NAME}_X.pkl and _O.pkl", flush=True)
        raise SystemExit

    if RUN_NAME == 'catchup':
        # Same two-separate-networks setup as 'twonet', plus a gate: whenever
        # O is falling behind X by more than CATCH_UP_MARGIN (measured by the
        # same value_error_vs_solver_by_mover metric used everywhere else in
        # this project), freeze X - X still PLAYS self-play games with its
        # current weights, but stops receiving gradient updates - so O trains
        # against a fixed target instead of a constantly-moving one, until it
        # closes the gap. Once it does, X unfreezes and both train together
        # again. This directly targets the "X never stops improving, so O can
        # never catch up" mechanism diagnosed in 04_bugs_lessons_and_limitations.md.
        CATCH_UP_MARGIN = float(sys.argv[5]) if len(sys.argv) > 5 else 0.05

        net_x = TicTacToeNet(hidden_size=64, seed=42)
        net_o = TicTacToeNet(hidden_size=64, seed=43)
        nets = {X: net_x, O: net_o}
        buffer_x = deque(maxlen=REPLAY_BUFFER_SIZE)
        buffer_o = deque(maxlen=REPLAY_BUFFER_SIZE)

        for iteration in range(NUM_ITERATIONS):
            iter_start = time.time()
            results = {'X': 0, 'O': 0, 'draw': 0}

            for _ in range(GAMES_PER_ITERATION):
                examples, winner = play_one_selfplay_game(nets, iterations=MCTS_ITERS,
                                                           temperature_moves=TEMPERATURE_MOVES, noise_frac=NOISE_FRAC)
                for ex in examples:
                    (buffer_x if ex[3] == X else buffer_o).append(ex)
                if winner == -1:
                    results['draw'] += 1
                elif winner == X:
                    results['X'] += 1
                else:
                    results['O'] += 1

            # Measure the CURRENT gap before deciding whether X is allowed to train this round.
            err_x, _ = value_error_vs_solver_by_mover(net_x, values)
            _, err_o = value_error_vs_solver_by_mover(net_o, values)
            gap = err_o - err_x  # positive means O is worse than X

            x_frozen = gap > CATCH_UP_MARGIN
            if x_frozen:
                value_loss_x, policy_loss_x = None, None  # skip training X entirely this round
            else:
                value_loss_x, policy_loss_x = train_on_examples(net_x, list(buffer_x))
            value_loss_o, policy_loss_o = train_on_examples(net_o, list(buffer_o))  # O always trains

            err = (err_x + err_o) / 2
            elapsed = time.time() - iter_start

            print(f"iter {iteration + 1:>4}/{NUM_ITERATIONS}: games={results}, "
                  f"buffer_x={len(buffer_x)}, buffer_o={len(buffer_o)}, x_frozen={x_frozen}, gap={gap:.4f}, "
                  f"value_loss_o={value_loss_o:.4f}, policy_loss_o={policy_loss_o:.4f}, "
                  f"value_error_vs_solver={err:.4f} (X={err_x:.4f}, O={err_o:.4f}), elapsed={elapsed:.1f}s", flush=True)

            log_writer.writerow([iteration + 1, results['X'], results['O'], results['draw'],
                                  len(buffer_x) + len(buffer_o),
                                  value_loss_x if value_loss_x is not None else -1, value_loss_o,
                                  err, err_x, err_o, elapsed])
            log_file.flush()

            if (iteration + 1) % CHECKPOINT_EVERY == 0:
                net_x.save(f'selfplay_trained_net_{RUN_NAME}_X.pkl')
                net_o.save(f'selfplay_trained_net_{RUN_NAME}_O.pkl')

        net_x.save(f'selfplay_trained_net_{RUN_NAME}_X.pkl')
        net_o.save(f'selfplay_trained_net_{RUN_NAME}_O.pkl')
        log_file.close()
        print(f"Done. Total time: {time.time() - start_time:.1f}s. "
              f"Saved to selfplay_trained_net_{RUN_NAME}_X.pkl and _O.pkl", flush=True)
        raise SystemExit

    if RUN_NAME == 'catchup_wr':
        # Same two-separate-networks setup as 'catchup', but the freeze gate is
        # driven by O's own ROLLING WIN RATE (win_rate_freeze_decision, see above)
        # instead of the value-calibration gap. The plain 'catchup' run showed that
        # gating on value_error_vs_solver_by_mover almost never engages, because
        # calibration and win rate are decoupled in this build - O's calibration
        # can look fine (or even better than X's) while O is still losing nearly
        # every game. This version watches the metric that's actually broken.
        FREEZE_THRESHOLD = float(sys.argv[5]) if len(sys.argv) > 5 else 0.15
        UNFREEZE_THRESHOLD = float(sys.argv[6]) if len(sys.argv) > 6 else 0.30
        WIN_RATE_WINDOW = int(sys.argv[7]) if len(sys.argv) > 7 else 10

        net_x = TicTacToeNet(hidden_size=64, seed=42)
        net_o = TicTacToeNet(hidden_size=64, seed=43)
        nets = {X: net_x, O: net_o}
        buffer_x = deque(maxlen=REPLAY_BUFFER_SIZE)
        buffer_o = deque(maxlen=REPLAY_BUFFER_SIZE)
        o_win_rate_history = []
        x_frozen = False

        for iteration in range(NUM_ITERATIONS):
            iter_start = time.time()
            results = {'X': 0, 'O': 0, 'draw': 0}

            for _ in range(GAMES_PER_ITERATION):
                examples, winner = play_one_selfplay_game(nets, iterations=MCTS_ITERS,
                                                           temperature_moves=TEMPERATURE_MOVES, noise_frac=NOISE_FRAC)
                for ex in examples:
                    (buffer_x if ex[3] == X else buffer_o).append(ex)
                if winner == -1:
                    results['draw'] += 1
                elif winner == X:
                    results['X'] += 1
                else:
                    results['O'] += 1

            o_win_rate_history.append(results['O'] / GAMES_PER_ITERATION)
            x_frozen = win_rate_freeze_decision(o_win_rate_history, FREEZE_THRESHOLD,
                                                 UNFREEZE_THRESHOLD, WIN_RATE_WINDOW, x_frozen)
            rolling_o_win_rate = (sum(o_win_rate_history[-WIN_RATE_WINDOW:]) / len(o_win_rate_history[-WIN_RATE_WINDOW:]))

            if x_frozen:
                value_loss_x, policy_loss_x = None, None  # skip training X entirely this round
            else:
                value_loss_x, policy_loss_x = train_on_examples(net_x, list(buffer_x))
            value_loss_o, policy_loss_o = train_on_examples(net_o, list(buffer_o))  # O always trains

            err_x, _ = value_error_vs_solver_by_mover(net_x, values)
            _, err_o = value_error_vs_solver_by_mover(net_o, values)
            err = (err_x + err_o) / 2
            elapsed = time.time() - iter_start

            print(f"iter {iteration + 1:>4}/{NUM_ITERATIONS}: games={results}, "
                  f"buffer_x={len(buffer_x)}, buffer_o={len(buffer_o)}, x_frozen={x_frozen}, "
                  f"o_win_rate_rolling={rolling_o_win_rate:.4f}, "
                  f"value_loss_o={value_loss_o:.4f}, policy_loss_o={policy_loss_o:.4f}, "
                  f"value_error_vs_solver={err:.4f} (X={err_x:.4f}, O={err_o:.4f}), elapsed={elapsed:.1f}s", flush=True)

            log_writer.writerow([iteration + 1, results['X'], results['O'], results['draw'],
                                  len(buffer_x) + len(buffer_o),
                                  value_loss_x if value_loss_x is not None else -1, value_loss_o,
                                  err, err_x, err_o, elapsed, x_frozen, rolling_o_win_rate])
            log_file.flush()

            if (iteration + 1) % CHECKPOINT_EVERY == 0:
                net_x.save(f'selfplay_trained_net_{RUN_NAME}_X.pkl')
                net_o.save(f'selfplay_trained_net_{RUN_NAME}_O.pkl')

        net_x.save(f'selfplay_trained_net_{RUN_NAME}_X.pkl')
        net_o.save(f'selfplay_trained_net_{RUN_NAME}_O.pkl')
        log_file.close()
        print(f"Done. Total time: {time.time() - start_time:.1f}s. "
              f"Saved to selfplay_trained_net_{RUN_NAME}_X.pkl and _O.pkl", flush=True)
        raise SystemExit

    # --- Every other run mode: one shared network ---
    net = TicTacToeNet(hidden_size=64, seed=42)
    net_save_path = f'selfplay_trained_net_{RUN_NAME}.pkl'
    replay_buffer = deque(maxlen=REPLAY_BUFFER_SIZE)

    for iteration in range(NUM_ITERATIONS):
        iter_start = time.time()
        results = {'X': 0, 'O': 0, 'draw': 0}

        for _ in range(GAMES_PER_ITERATION):
            examples, winner = play_one_selfplay_game(net, iterations=MCTS_ITERS, teacher_side=TEACHER_SIDE,
                                                       temperature_moves=TEMPERATURE_MOVES, noise_frac=NOISE_FRAC,
                                                       extra_iterations_side=EXTRA_ITERATIONS_SIDE,
                                                       imitate_teacher_policy=IMITATE_TEACHER_POLICY)
            replay_buffer.extend(examples)
            if winner == -1:
                results['draw'] += 1
            elif winner == X:
                results['X'] += 1
            else:
                results['O'] += 1

        # Train on the whole buffer (recent iterations' worth of games, not just
        # this iteration's 20) - balance_by_mover (inside train_on_examples) then
        # equalizes the X-to-move vs O-to-move split within that larger pool.
        value_loss, policy_loss = train_on_examples(net, list(replay_buffer))
        err = value_error_vs_solver(net, values)
        err_x, err_o = value_error_vs_solver_by_mover(net, values)
        elapsed = time.time() - iter_start

        print(f"iter {iteration + 1:>4}/{NUM_ITERATIONS}: games={results}, buffer={len(replay_buffer)}, "
              f"value_loss={value_loss:.4f}, policy_loss={policy_loss:.4f}, "
              f"value_error_vs_solver={err:.4f} (X={err_x:.4f}, O={err_o:.4f}), elapsed={elapsed:.1f}s", flush=True)

        log_writer.writerow([iteration + 1, results['X'], results['O'], results['draw'],
                              len(replay_buffer), value_loss, policy_loss, err, err_x, err_o, elapsed])
        log_file.flush()

        if (iteration + 1) % CHECKPOINT_EVERY == 0:
            net.save(net_save_path)

    net.save(net_save_path)
    log_file.close()
    print(f"Done. Total time: {time.time() - start_time:.1f}s. Saved to {net_save_path}", flush=True)
